In [17]:
# Join two arrays
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))

print(arr)

 


[1 2 3 4 5 6]


In [21]:
# Join two 2-D arrays along rows (axis=1):
# axis = 0 means along column by default

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [22]:
# Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [23]:
# NumPy provides a helper function: hstack() to stack along rows.

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


In [24]:
#NumPy provides a helper function: vstack()  to stack along columns.

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [25]:
# NumPy provides a helper function: dstack() to stack along height, which is the same as depth.
 
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)


[[[1 4]
  [2 5]
  [3 6]]]
