In [1]:
# Iterate on the elements of the following 1-D array:

import numpy as np
arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


In [2]:
# Iterate on the elements of the following 2-D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [3]:
#Iterate on each scalar element of the 2-D array:
 
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [4]:
#Iterate on the elements of the following 3-D array:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [5]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [6]:
#The function nditer() is a helping function that can be used from very basic to very advanced iterations. 
#It solves some basic issues which we face in iteration
#np.ndtir is shortcut to nested for ...
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [15]:
# Here we Iterate 4 diamention array using np.nditer()
arr = np.array([[[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]],[[13,14],[15,16]]]])
print("array of dimension",arr.ndim)

for x in np.nditer(arr):
    print(x)

array of dimension 4
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [16]:
# Iterate through every scalar element of the 2D array skipping 1 element:
 
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


In [17]:
# Enumeration means mentioning sequence number of somethings one by one.
# Sometimes we require corresponding index of the element while iterating, 
# the ndenumerate() method can be used for those usecases.

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [19]:
# Enumerate on following 2D array's elements:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for id, x in np.ndenumerate(arr):
    print(id, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
