In [1]:
import numpy as np
#The copy SHOULD NOT be affected by the changes made to the original array.
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [2]:
#The view SHOULD be affected by the changes made to the original array.
arr2 = np.array([1, 2, 3, 4, 5])
x = arr2.view()
arr2[0] = 42

print(arr2)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [3]:
#This example  returns (2, 4), which means that the array has 2 dimensions, and each dimension has 4 elements.
arr3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr3.shape)


(2, 4)


In [4]:
# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 
#and verify that last dimension has value 4:
arr4 = np.array([1, 2, 3, 4], ndmin=5)

print(arr4)
print('shape of array :', arr4.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [7]:
#Convert the following 1-D array with 12 elements into a 2-D array.
# The outermost dimension will have 4 arrays, each with 3 elements:
arr5 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr5.reshape(4, 3)

print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
# Convert the following 1-D array with 12 elements into a 3-D array.
# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:
arr6 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr6.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [9]:
# Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
# Pass -1 as the value, and NumPy will calculate this number for you.
arr7 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr7.reshape(2, 2, -1)

print(newarr)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
# Flattening array means converting a multidimensional array into a 1D array.
# We can use reshape(-1) to do this.
arr8 = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr8.reshape(-1)

print(newarr)

[1 2 3 4 5 6]
