In [2]:
# Difference between numpy array and list
# Array is of same data type and list may contain different datatypes
# We can not operate functions on elements of list simultaneously
import numpy as np
number = np.array([2,4,6,8,10,12,14,16,18,20])
print(number)

[ 2  4  6  8 10 12 14 16 18 20]


In [3]:
number*2
#Here we directly apply functions on each element in array

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [4]:
name = np.array(['Apoorv','Marvel','America','Monica'])
print(name)

['Apoorv' 'Marvel' 'America' 'Monica']


In [5]:
'Captain' + ' ' + name[0]
#or we can operate on individually

'Captain Apoorv'

In [6]:
# Here we used array() function to create numpy array
# Similarly there are many functions to create numpy array
# array(),arange(),zeros(),ones(),linespace(),eye(),random().etc

In [20]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

In [7]:
#array()  

#we used array() function to create numpy array from list or tuple
a = np.array([1,2,3])#list
b = np.array((1,2,3))#tuple

oneD = np.array([1,2,3])#one dimension
twoD = np.array([[1,2],[3,4],[5,6]])#two dimension
threeD = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

intToFloat = np.array([1,2,3],"float")#type cast
intToComp  = np.array([1,2,3],"complex")#type cast

In [8]:
print(a)
print(b)
print(oneD)
print(twoD)
print(threeD)
print(intToFloat)
print(intToComp)

[1 2 3]
[1 2 3]
[1 2 3]
[[1 2]
 [3 4]
 [5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
[1. 2. 3.]
[1.+0.j 2.+0.j 3.+0.j]


In [9]:
print(oneD.ndim)
print(twoD.ndim)
print(threeD.ndim)
# "array_name.ndim"   gives dimensions of respective array

1
2
3


In [10]:
# here we set by default dimension of array while declaring it
setdim = np.array([1,2,3,4], ndmin = 5)   #ndmin = nth dimension minimum
print(setdim)
print(setdim.ndim) 

[[[[[1 2 3 4]]]]]
5


In [11]:
# Access the 5th element on 2nd dim:
arr1 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd dim: ', arr1[1, 4])

5th element on 2nd dim:  10


In [12]:
# Access the third element of the second array of the first array:
arr2 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr2[0, 1, 2])

6


In [13]:
# Print the last element from the 2nd dim:
arr3 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr3[1, -1])

Last element from 2nd dim:  10


In [14]:
# Slice elements from index 1 to index 5 from the following array
arr4 = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr4[1:5])

[2 3 4 5]


In [15]:
# Slice elements from the beginning to index 4 (not included):
arr5 = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr5[:4])

[1 2 3 4]


In [16]:
# Slice from the index 3 from the end to index 1 from the end:
arr6 = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr6[-3:-1])

[5 6]


In [17]:
# Return every other element from index 1 to index 5:
arr7 = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr7[1:5:2])

[2 4]


In [18]:
#From the second element, slice elements from index 1 to index 4 (not included):
arr8 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr8[1, 1:4])

[7 8 9]


In [19]:
# From both elements, return index 2:
arr9 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr9[0:2, 2])

[3 8]


In [21]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   